use crate::merge::MergedSegment;
use std::collections::{BTreeMap, HashSet};

/// Format seconds as HH:MM:SS
fn format_timestamp(seconds: f64) -> String {
    let total_secs = seconds as u64;
    let hours = total_secs / 3600;
    let minutes = (total_secs % 3600) / 60;
    let secs = total_secs % 60;
    format!("{:02}:{:02}:{:02}", hours, minutes, secs)
}

/// Group segments into time blocks by minute
fn group_by_time_blocks(
    segments: &[MergedSegment],
    block_minutes: u32,
) -> BTreeMap<u32, Vec<&MergedSegment>> {
    let mut blocks: BTreeMap<u32, Vec<&MergedSegment>> = BTreeMap::new();

    for seg in segments {
        let mins = seg.start / 60.0;
        let block_index = (mins / block_minutes as f64) as u32;
        blocks.entry(block_index).or_default().push(seg);
    }

    blocks
}

/// Generate a markdown transcript from merged segments
pub fn export_transcript_markdown(segments: &[MergedSegment]) -> String {
    if segments.is_empty() {
        return "# Meeting Transcript\n\n*No segments recorded.*\n".to_string();
    }

    let mut md = String::new();

    // Header
    md.push_str("# Meeting Transcript\n\n");

    // Duration
    let duration = segments.last().map(|s| s.end).unwrap_or(0.0);
    md.push_str(&format!(
        "**Duration:** {}\n\n",
        format_timestamp(duration)
    ));

    // Participant count
    let speakers: HashSet<&str> = segments.iter().map(|s| s.speaker.as_str()).collect();
    md.push_str(&format!("**Participants:** {}\n\n", speakers.len()));

    md.push_str("---\n\n");

    // Time blocks (1-minute)
    let blocks = group_by_time_blocks(segments, 1);

    for (&block_index, block_segments) in &blocks {
        let block_start_secs = block_index as f64 * 60.0;
        let block_end_secs = block_start_secs + 60.0;

        md.push_str(&format!(
            "## {} – {}\n\n",
            format_timestamp(block_start_secs),
            format_timestamp(block_end_secs)
        ));

        for seg in block_segments {
            md.push_str(&format!(
                "**{}** `[{}]`: {}\n\n",
                seg.speaker,
                format_timestamp(seg.start),
                seg.text.trim()
            ));
        }
    }

    md.push_str("---\n\n");
    md.push_str("*Generated by MeetingScribe*\n");

    md
}

/// Sanitize a string for use as a filename
pub fn sanitize_filename(s: &str) -> String {
    s.chars()
        .map(|c| match c {
            ' ' | '\t' => '_',
            '/' | '\\' | ':' | '*' | '?' | '"' | '<' | '>' | '|' => '_',
            c if c.is_alphanumeric() || c == '_' || c == '-' || c == '.' => c,
            _ => '_',
        })
        .collect::<String>()
        .trim_matches('_')
        .to_string()
}
