use crate::merge::MergedSegment;
use serde::{Deserialize, Serialize};
use std::collections::{BTreeMap, BTreeSet, HashSet};

/// An image pasted by the user during recording, with its recording timecode.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ImageAnnotation {
    /// Absolute path to the image in the temp directory.
    pub path: String,
    /// Seconds elapsed since recording started when the image was pasted.
    pub timecode_secs: f64,
}

/// Format seconds as HH:MM:SS
pub fn format_timestamp(seconds: f64) -> String {
    let total_secs = seconds as u64;
    let hours = total_secs / 3600;
    let minutes = (total_secs % 3600) / 60;
    let secs = total_secs % 60;
    format!("{:02}:{:02}:{:02}", hours, minutes, secs)
}

/// Group segments into time blocks by minute
fn group_by_time_blocks(
    segments: &[MergedSegment],
    block_minutes: u32,
) -> BTreeMap<u32, Vec<&MergedSegment>> {
    let mut blocks: BTreeMap<u32, Vec<&MergedSegment>> = BTreeMap::new();

    for seg in segments {
        let mins = seg.start / 60.0;
        let block_index = (mins / block_minutes as f64) as u32;
        blocks.entry(block_index).or_default().push(seg);
    }

    blocks
}

/// Generate a markdown transcript from merged segments, optionally embedding image annotations.
pub fn export_transcript_markdown(
    segments: &[MergedSegment],
    image_annotations: &[ImageAnnotation],
) -> String {
    if segments.is_empty() && image_annotations.is_empty() {
        return "# Meeting Transcript\n\n*No segments recorded.*\n".to_string();
    }

    let mut md = String::new();

    // Header
    md.push_str("# Meeting Transcript\n\n");

    // Duration
    let duration = segments.last().map(|s| s.end).unwrap_or(0.0);
    md.push_str(&format!(
        "**Duration:** {}\n\n",
        format_timestamp(duration)
    ));

    // Participant count
    let speakers: HashSet<&str> = segments.iter().map(|s| s.speaker.as_str()).collect();
    md.push_str(&format!("**Participants:** {}\n\n", speakers.len()));

    md.push_str("---\n\n");

    // Build a map of block_index -> images sorted by timecode
    let mut image_blocks: BTreeMap<u32, Vec<&ImageAnnotation>> = BTreeMap::new();
    for img in image_annotations {
        let block_index = (img.timecode_secs / 60.0) as u32;
        image_blocks.entry(block_index).or_default().push(img);
    }

    // Time blocks (1-minute) — include blocks that have only images too
    let segment_blocks = group_by_time_blocks(segments, 1);
    let mut all_block_indices: BTreeSet<u32> = segment_blocks.keys().cloned().collect();
    all_block_indices.extend(image_blocks.keys().cloned());

    for block_index in &all_block_indices {
        let block_start_secs = *block_index as f64 * 60.0;
        let block_end_secs = block_start_secs + 60.0;

        md.push_str(&format!(
            "## {} – {}\n\n",
            format_timestamp(block_start_secs),
            format_timestamp(block_end_secs)
        ));

        // Interleave segments and images in timecode order within this block
        let empty_segs: Vec<&MergedSegment> = vec![];
        let segs = segment_blocks.get(block_index).unwrap_or(&empty_segs);
        let imgs = image_blocks.get(block_index).map(|v| v.as_slice()).unwrap_or(&[]);

        let mut seg_iter = segs.iter().peekable();
        let mut img_iter = imgs.iter().peekable();

        loop {
            let next_seg_time = seg_iter.peek().map(|s| s.start);
            let next_img_time = img_iter.peek().map(|i| i.timecode_secs);

            match (next_seg_time, next_img_time) {
                (None, None) => break,
                (Some(_), None) => {
                    let seg = seg_iter.next().unwrap();
                    md.push_str(&format!(
                        "**{}** `[{}]`: {}\n\n",
                        seg.speaker,
                        format_timestamp(seg.start),
                        seg.text.trim()
                    ));
                }
                (None, Some(_)) => {
                    let img = img_iter.next().unwrap();
                    md.push_str(&render_image_annotation(img));
                }
                (Some(st), Some(it)) => {
                    if st <= it {
                        let seg = seg_iter.next().unwrap();
                        md.push_str(&format!(
                            "**{}** `[{}]`: {}\n\n",
                            seg.speaker,
                            format_timestamp(seg.start),
                            seg.text.trim()
                        ));
                    } else {
                        let img = img_iter.next().unwrap();
                        md.push_str(&render_image_annotation(img));
                    }
                }
            }
        }
    }

    md.push_str("---\n\n");
    md.push_str("*Generated by Sidekick2000*\n");

    md
}

fn render_image_annotation(img: &ImageAnnotation) -> String {
    let ts = format_timestamp(img.timecode_secs);
    let basename = std::path::Path::new(&img.path)
        .file_name()
        .map(|n| n.to_string_lossy().into_owned())
        .unwrap_or_default();
    format!(
        "> 📸 *Screenshot at {}*\n\n![Screenshot at {}](./screenshots/{}) \n\n",
        ts, ts, basename
    )
}

/// Sanitize a string for use as a filename
pub fn sanitize_filename(s: &str) -> String {
    s.chars()
        .map(|c| match c {
            ' ' | '\t' => '_',
            '/' | '\\' | ':' | '*' | '?' | '"' | '<' | '>' | '|' => '_',
            c if c.is_alphanumeric() || c == '_' || c == '-' || c == '.' => c,
            _ => '_',
        })
        .collect::<String>()
        .trim_matches('_')
        .to_string()
}
